# Generated by Django 3.1.1 on 2020-09-08 15:52

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        BtreeGinExtension(),
        migrations.CreateModel(
            name="MusicWork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iswc",
                    models.CharField(
                        db_index=True, max_length=11, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=300)),
                (
                    "contributors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="musicwork",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["contributors"], name="works_music_contrib_324132_gin"
            ),
        ),
    ]
