# Generated by Django 3.1.1 on 2020-09-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicwork',
            name='iswc',
            field=models.CharField(db_index=True, max_length=11, null=True),
        ),
        migrations.AddConstraint(
            model_name='musicwork',
            constraint=models.UniqueConstraint(condition=models.Q(iswc__isnull=False), fields=('iswc',), name='idx_unique_iswc'),
        ),
    ]
